version: 2.0
jobs:
  build:
    docker:
      - image: advaitkukade/serverside1:1.0 
    working_directory: /serverdata   
    steps:
      - run: echo "Created Successfully."
     #- run: docker run -it serverside1:1.0 sh 
      - run: apk add --no-cache ca-certificates
      - run: 
          name: Creating Dummy Artifacts
          command: | 
            echo "My Artifact File" > /serverdata/artifact1.txt;
            mkdir /home/artifacts/
            echo "My Artifact file in another directory" > /home/artifact-home.txt
      
      - store_artifacts:
          path: /serverdata/artifact1.txt
      
      - store_artifacts:
          path: /home/artifact-home.txt
      
    # - store_test_results:
    #     path: /home/test-results.xml
      
      - run: echo "Artifacts created and stored." 
     
workflows:
  workflows_1:
    jobs:
      - build
      
